**1. Create a 3x3x3 array with random values**

In [50]:
import numpy as np
c = np.array([[1,2,4],[11,23,5],[3,7,9]])
print(c)
Z = np.random.random((3,3,3))
print(Z)

[[ 1  2  4]
 [11 23  5]
 [ 3  7  9]]
[[[0.41327218 0.51263764 0.46978091]
  [0.96047337 0.89802592 0.36145855]
  [0.3971021  0.55665035 0.73410826]]

 [[0.76282004 0.32927348 0.67625413]
  [0.27975046 0.65364436 0.14011349]
  [0.48918241 0.23832331 0.89108227]]

 [[0.95446818 0.6555799  0.3511302 ]
  [0.22109133 0.20345158 0.42753487]
  [0.15489055 0.32563249 0.26058857]]]


**2.Create a 5x5 matrix with values 1,2,3,4 just below the diagonal**

In [5]:
a = np.diag(1+np.arange(4),k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


**3.Create a 8x8 matrix and fill it with a checkerboard pattern**

In [7]:
b = np.zeros((8,8),dtype=int)
b[1::2,::2] = 1
b[::2,1::2] = 1
print(b)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


**4. Normalize a 5x5 random matrix**

In [9]:
d = np.random.random((5,5))
d = (d - np.mean (d)) / (np.std (d))
print(d)

[[ 1.1949648  -0.43305745 -0.93276118 -0.33206587 -0.33016007]
 [-0.40366284  1.2508433   1.30031608 -1.21842974 -0.33001724]
 [-1.03790451 -1.73206445 -0.01818914  1.40332169 -1.66207437]
 [ 0.07666804 -0.33343062 -0.2219525   1.56665963 -1.15529613]
 [ 1.41881674 -0.32473964  1.13548606  1.05174067  0.06698875]]


**5. How to find common values between two arrays?**

In [12]:
a1 = np.random.randint(0,10,10)
a2 = np.random.randint(0,10,10)
print(np.intersect1d(a1,a2))

[0 1 2 5 7]


**6.How to get the dates of yesterday, today and tomorrow?**

In [52]:
yesterday = np.datetime64('today') - np.timedelta64(1)
today     = np.datetime64('today')
tomorrow  = np.datetime64('today') + np.timedelta64(1)
print("Yesterday\'s date was: ",yesterday)
print("Today\'s date is: ",today)
print("Tomorrow\'s date is: ",tomorrow)

Yesterday's date was:  2020-07-30
Today's date is:  2020-07-31
Tomorrow's date is:  2020-08-01


**7. Consider two random array A and B, check if they are equal**

In [20]:
A = np.random.randint(0,1,2)
B = np.random.randint(0,1,2)

equal = np.allclose(A,B)
print(equal)

equal = np.array_equal(A,B)
print(equal)


True
True


**8.Create random vector of size 10 and replace the maximum value by 0**

In [58]:
a = np.random.random(10)
a[a.argmax()] = 0
print(a.argmax())
print(a)

9
[0.36415671 0.06073392 0.48073857 0.42255314 0.76959605 0.32640933
 0.         0.73190617 0.14393529 0.86627922]


**9. How to print all the values of an array?**

In [54]:
np.set_printoptions(threshold=float("inf"))
a = np.ones((12,12))
print(a)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


**10.Subtract the mean of each row of a matrix**

In [55]:
A = np.random.rand(5, 10)

B = A - A.mean(axis=1, keepdims=True)
print(B)

[[ 0.37779774 -0.15423225  0.28173563 -0.49500383  0.12840053 -0.38501344
  -0.4915521   0.15351605  0.35263056  0.23172112]
 [-0.14934979 -0.29778966 -0.28914403 -0.05783288 -0.06895101  0.02759014
   0.15291382  0.58985515 -0.34588723  0.43859549]
 [ 0.14787049  0.07258518 -0.17231551  0.03283186  0.18016313 -0.02052004
   0.41398359 -0.06065118 -0.05876004 -0.53518749]
 [ 0.39736761  0.16111143 -0.48266427 -0.00141213 -0.18034842 -0.3004076
   0.30546683 -0.4500241   0.38991373  0.16099691]
 [ 0.2117698  -0.01004074 -0.15668852 -0.18175454  0.22496849  0.23893265
   0.0149843   0.15992931 -0.21191154 -0.29018919]]


**11.Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)?**

In [33]:
Z = np.ones(8)
I = np.random.randint(0,len(Z),16)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[5. 3. 3. 3. 2. 2. 2. 4.]
[9. 5. 5. 5. 3. 3. 3. 7.]


**12.How to get the diagonal of a dot product?**

In [36]:
A = np.random.uniform(0,1,(4,4))
B = np.random.uniform(0,1,(4,4))
print(A)
print(B)

prod=np.sum(A * B.T, axis=1)
print("diagonal of a dot product is : ",prod)

[[0.77760001 0.30028325 0.76803258 0.358567  ]
 [0.87792471 0.04120568 0.65015963 0.0133918 ]
 [0.42768581 0.98979302 0.05993064 0.10105921]
 [0.51814463 0.15160832 0.19615925 0.86624371]]
[[0.31424717 0.44822177 0.49204866 0.95986845]
 [0.90922359 0.42404819 0.39844282 0.31450396]
 [0.18088124 0.95297172 0.52124168 0.78300676]
 [0.94079606 0.23254898 0.00439851 0.57351421]]
diagonal of a dot product is :  [0.99364433 1.03367614 0.63650101 1.19542919]


**13.How to find the most frequent value in an array?**

In [61]:
a = np.random.randint(0,10,35)
print(a)
print(np.bincount(a).argmax())

[3 4 7 6 2 2 0 2 6 3 7 4 9 5 8 2 9 8 6 3 9 8 7 5 5 5 6 2 7 5 0 5 8 0 6]
5


**14.How to get the n largest values of an array**

In [64]:
a = np.arange(1000)
np.random.shuffle(a)
n = 5

print(a[np.argsort(a)[-n:]])


[995 996 997 998 999]


**15.How to create a record array from a regular array?**

In [45]:
a = np.array([("hi", 1, 1),
              ("all", 2.6, 3)])
b = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(b)

[(b'hi', 1. , 1) (b'all', 2.6, 3)]
